<?php

namespace Database\Seeders;

use App\Core\Domain\Catalog\Models\Category;
use App\Core\Domain\Catalog\Models\Trade;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TradeSeeder extends Seeder
{
    public function run(): void
    {
        $categoryIdsBySlug = Category::query()->pluck('id', 'slug');
        $rows = [];

        foreach ($this->definitions() as $categorySlug => $trades) {
            $categoryId = $categoryIdsBySlug[$categorySlug] ?? null;
            if ($categoryId === null) {
                continue;
            }

            foreach ($trades as $trade) {
                $slug = Str::slug($trade['en']);
                $rows[] = [
                    'category_id' => $categoryId,
                    'slug' => $slug,
                    'name' => json_encode(['fr' => $trade['fr'], 'en' => $trade['en']], JSON_UNESCAPED_UNICODE),
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            }
        }

        Trade::upsert($rows, ['category_id', 'slug'], ['name', 'is_active', 'updated_at']);
    }

    /**
     * @return array<string, list<array{fr: string, en: string}>>
     */
    private function definitions(): array
    {
        return [
            // ==================== BTP & INDUSTRIE ====================
            'construction-structural-work' => [
                ['fr' => 'Maçon', 'en' => 'Mason'],
                ['fr' => 'Coffreur-boiseur', 'en' => 'Formwork carpenter'],
                ['fr' => 'Ferrailleur', 'en' => 'Steel fixer'],
                ['fr' => 'Manœuvre BTP', 'en' => 'Construction laborer'],
                ['fr' => 'Chef de chantier', 'en' => 'Site supervisor'],
                ['fr' => 'Conducteur de travaux', 'en' => 'Works manager'],
                ['fr' => 'Géomètre', 'en' => 'Surveyor'],
                ['fr' => 'Bétonnier', 'en' => 'Concrete worker'],
                ['fr' => 'Ouvrier en voirie', 'en' => 'Road worker'],
                ['fr' => 'Poseur de canalisations', 'en' => 'Pipe layer'],
                ['fr' => 'Terrassier', 'en' => 'Earthworks operator'],
                ['fr' => 'Démolisseur', 'en' => 'Demolition worker'],
                ['fr' => 'Foreur de fondations', 'en' => 'Foundation driller'],
                ['fr' => 'Pieux-foré / Pieux-battu opérateur', 'en' => 'Pile driving operator'],
                ['fr' => 'Coffreur-dalle', 'en' => 'Slab formwork carpenter'],
                ['fr' => 'Poseur de préfabriqués', 'en' => 'Precast concrete erector'],
                ['fr' => 'Ouvrier en assainissement', 'en' => 'Drainage worker'],
            ],
            'construction-finishing-work' => [
                ['fr' => 'Plombier', 'en' => 'Plumber'],
                ['fr' => 'Peintre en bâtiment', 'en' => 'Building painter'],
                ['fr' => 'Carreleur', 'en' => 'Tiler'],
                ['fr' => 'Plâtrier', 'en' => 'Plasterer'],
                ['fr' => 'Staffeur-ornemaniste', 'en' => 'Ornamental plasterer (staff)'],
                ['fr' => 'Menuisier', 'en' => 'Carpenter'],
                ['fr' => 'Électricien de chantier', 'en' => 'Construction electrician'],
                ['fr' => 'Fabricant d’agencements', 'en' => 'Fit-out joiner'],
                ['fr' => 'Poseur de revêtements', 'en' => 'Flooring fitter'],
                ['fr' => 'Isolateur', 'en' => 'Insulation worker'],
                ['fr' => 'Menuisier PVC / aluminium', 'en' => 'PVC/aluminium joiner'],
                ['fr' => 'Couvreur', 'en' => 'Roofer'],
                ['fr' => 'Zingueur', 'en' => 'Zinc worker / Sheet metal roofer'],
                ['fr' => 'Vitrier', 'en' => 'Glazier'],
                ['fr' => 'Climaticien', 'en' => 'HVAC technician'],
                ['fr' => 'Frigoriste', 'en' => 'Refrigeration technician'],
                ['fr' => 'Chauffagiste', 'en' => 'Heating technician'],
                ['fr' => 'Parqueteur', 'en' => 'Parquet floor fitter'],
                ['fr' => 'Poseur de moquette', 'en' => 'Carpet fitter'],
                ['fr' => 'Poseur de faux plafond', 'en' => 'Suspended ceiling installer'],
                ['fr' => 'Poseur de cloisons sèches', 'en' => 'Drywall partition installer'],
                ['fr' => 'Monteur de cloisons amovibles', 'en' => 'Movable partition installer'],
                ['fr' => 'Poseur de stores et volets roulants', 'en' => 'Blind and shutter installer'],
                ['fr' => 'Poseur de gazon', 'en' => 'Turf layer'],
                ['fr' => 'Poseur de revêtements de sol sportifs', 'en' => 'Sports flooring fitter'],
                ['fr' => 'Installateur de cuisine', 'en' => 'Kitchen fitter'],
                ['fr' => 'Installateur de salle de bain', 'en' => 'Bathroom fitter'],
            ],
            'heavy-machinery-operation' => [
                ['fr' => 'Conducteur d\'engins de chantier', 'en' => 'Construction equipment operator'],
                ['fr' => 'Grutier', 'en' => 'Crane operator'],
                ['fr' => 'Conducteur de pelleteuse', 'en' => 'Excavator operator'],
                ['fr' => 'Conducteur de bulldozer', 'en' => 'Bulldozer operator'],
                ['fr' => 'Conducteur de tractopelle', 'en' => 'Backhoe loader operator'],
                ['fr' => 'Conducteur de chargeuse', 'en' => 'Wheel loader operator'],
                ['fr' => 'Conducteur de niveleuse', 'en' => 'Grader operator'],
                ['fr' => 'Conducteur de compacteur', 'en' => 'Roller operator'],
                ['fr' => 'Conducteur de grue mobile', 'en' => 'Mobile crane operator'],
                ['fr' => 'Conducteur d\'engins de manutention', 'en' => 'Material handling equipment operator'],
                ['fr' => 'Conducteur de centrale à béton', 'en' => 'Concrete plant operator'],
                ['fr' => 'Conducteur de concasseur', 'en' => 'Crusher operator'],
                ['fr' => 'Conducteur de cribleur', 'en' => 'Screening plant operator'],
                ['fr' => 'Foreur', 'en' => 'Drilling rig operator'],
                ['fr' => 'Pilote de Marteau-piqueur', 'en' => 'Jackhammer operator'],
            ],
            'industrial-maintenance' => [
                ['fr' => 'Technicien de maintenance industrielle', 'en' => 'Industrial maintenance technician'],
                ['fr' => 'Mécanicien industriel', 'en' => 'Industrial mechanic'],
                ['fr' => 'Électromécanicien', 'en' => 'Electromechanic'],
                ['fr' => 'Automaticien', 'en' => 'Automation technician'],
                ['fr' => 'Technicien de maintenance des machines-outils', 'en' => 'Machine tool maintenance technician'],
                ['fr' => 'Responsable maintenance', 'en' => 'Maintenance manager'],
                ['fr' => 'Technicien en CND (contrôle non destructif)', 'en' => 'NDT technician'],
                ['fr' => 'Roboticien', 'en' => 'Robotics technician'],
                ['fr' => 'Instrumentiste', 'en' => 'Instrumentation technician'],
                ['fr' => 'Calibreur', 'en' => 'Calibration technician'],
                ['fr' => 'Lubrificateur', 'en' => 'Lubrication technician'],
                ['fr' => 'Soudeur de maintenance', 'en' => 'Maintenance welder'],
                ['fr' => 'Vibracoupeur / Contrôleur de vibrations', 'en' => 'Vibration analyst'],
            ],
            'welding-metallurgy' => [
                ['fr' => 'Soudeur', 'en' => 'Welder'],
                ['fr' => 'Chaudronnier', 'en' => 'Boilermaker'],
                ['fr' => 'Serrurier-métallier', 'en' => 'Metalworker-locksmith'],
                ['fr' => 'Tuyauteur', 'en' => 'Pipe fitter'],
                ['fr' => 'Soudeur TIG', 'en' => 'TIG welder'],
                ['fr' => 'Soudeur MIG/MAG', 'en' => 'MIG/MAG welder'],
                ['fr' => 'Soudeur à l\'arc', 'en' => 'Arc welder'],
                ['fr' => 'Constructeur métallique', 'en' => 'Structural metal fabricator'],
                ['fr' => 'Traceur / découpeur', 'en' => 'Marker / cutter'],
                ['fr' => 'Soudeur sous-marin', 'en' => 'Underwater welder'],
                ['fr' => 'Calorifugeur', 'en' => 'Thermal insulation worker (pipes)'],
                ['fr' => 'Tôlier', 'en' => 'Sheet metal worker'],
                ['fr' => 'Ajusteur-mécanicien', 'en' => 'Fitter-mechanic'],
                ['fr' => 'Décolleteur', 'en' => 'CNC turner / Screw machine operator'],
                ['fr' => 'Fraiseur', 'en' => 'Milling machine operator'],
                ['fr' => 'Rectifieur', 'en' => 'Grinder (precision machining)'],
                ['fr' => 'Usineur', 'en' => 'Machinist'],
                ['fr' => 'Opérateur CNC', 'en' => 'CNC operator'],
                ['fr' => 'Fondeur', 'en' => 'Founder / Metal caster'],
                ['fr' => 'Mouleur', 'en' => 'Molder'],
                ['fr' => 'Monteur de structures métalliques', 'en' => 'Steel erector'],
            ],
            'manufacturing' => [
                ['fr' => 'Opérateur de production', 'en' => 'Production operator'],
                ['fr' => 'Technicien en automatismes', 'en' => 'Automation technician'],
                ['fr' => 'Électricien industriel', 'en' => 'Industrial electrician'],
                ['fr' => 'Contrôleur qualité', 'en' => 'Quality controller'],
                ['fr' => 'Responsable de production', 'en' => 'Production manager'],
                ['fr' => 'Opérateur de ligne d’emballage', 'en' => 'Packaging line operator'],
                ['fr' => 'Conducteur de machine de production', 'en' => 'Production machine operator'],
                ['fr' => 'Régleur', 'en' => 'Machine setter'],
                ['fr' => 'Technicien de process', 'en' => 'Process technician'],
                ['fr' => 'Ouvrier de fabrication', 'en' => 'Factory worker'],
                ['fr' => 'Technicien en plasturgie', 'en' => 'Plastics technician'],
                ['fr' => 'Opérateur d\'injection plastique', 'en' => 'Plastic injection operator'],
                ['fr' => 'Opérateur d\'impression 3D', 'en' => '3D printing operator'],
                ['fr' => 'Souffleur de verre industriel', 'en' => 'Industrial glassblower'],
                ['fr' => 'Opérateur de ligne de conditionnement', 'en' => 'Packaging line operator'],
                ['fr' => 'Agent de conditionnement', 'en' => 'Packaging worker'],
                ['fr' => 'Expéditionnaire', 'en' => 'Shipping clerk'],
                ['fr' => 'Mouleur en fonderie', 'en' => 'Foundry molder'],
            ],
            'skilled-labor' => [
                ['fr' => 'Ouvrier qualifié', 'en' => 'Skilled worker'],
                ['fr' => 'Technicien polyvalent', 'en' => 'Multiskilled technician'],
                ['fr' => 'Ouvrier de maintenance', 'en' => 'Maintenance worker'],
                ['fr' => 'Agent de fabrication', 'en' => 'Production agent'],

            ],
            'carpentry-woodwork' => [
                ['fr' => 'Menuisier', 'en' => 'Carpenter'],
                ['fr' => 'Ébéniste', 'en' => 'Cabinetmaker'],
                ['fr' => 'Charpentier', 'en' => 'Timber framer'],
                ['fr' => 'Agenceur', 'en' => 'Furniture installer'],
                ['fr' => 'Tourneur sur bois', 'en' => 'Wood turner'],
                ['fr' => 'Sculpteur sur bois', 'en' => 'Wood carver'],
                ['fr' => 'Marqueteur', 'en' => 'Marquetry worker'],
                ['fr' => 'Scieur', 'en' => 'Sawyer'],
                ['fr' => 'Dérouleur / Ébéniste de plaquage', 'en' => 'Veneer peeling operator'],
                ['fr' => 'Menuisier de prestige', 'en' => 'Premium carpenter'],
                ['fr' => 'Constructeur de charpente traditionnelle', 'en' => 'Traditional timber framer'],
                ['fr' => 'Menuisier en agencement de cuisine', 'en' => 'Kitchen fit-out carpenter'],
            ],
            'construction-civil-engineering' => [
                ['fr' => 'Ingénieur civil', 'en' => 'Civil engineer'],
                ['fr' => 'Ingénieur structure', 'en' => 'Structural engineer'],
                ['fr' => 'Économiste de la construction', 'en' => 'Construction cost estimator'],
                ['fr' => 'Métreur', 'en' => 'Quantity surveyor'],
                ['fr' => 'Dessinateur-projeteur BTP', 'en' => 'Construction draftsman'],
                ['fr' => 'Ingénieur géotechnicien', 'en' => 'Geotechnical engineer'],
                ['fr' => 'Chef de projet BTP', 'en' => 'Construction project manager'],
                ['fr' => 'Ingénieur travaux publics', 'en' => 'Public works engineer'],
                ['fr' => 'Ingénieur BIM', 'en' => 'BIM engineer'],
                ['fr' => 'Diagnostiqueur immobilier', 'en' => 'Building diagnostician'],
                ['fr' => 'Contrôleur technique en construction', 'en' => 'Construction technical inspector'],
                ['fr' => 'Coordinateur SPS', 'en' => 'Construction health and safety coordinator'],
                ['fr' => 'Ordonnancement de chantier', 'en' => 'Construction scheduler'],
                ['fr' => 'Maître d\'œuvre', 'en' => 'Lead contractor / Project supervisor'],
                ['fr' => 'Ingénieur ERP / Sécurité incendie bâtiment', 'en' => 'Building fire safety engineer'],
                ['fr' => 'Topographe', 'en' => 'Topographer'],
                ['fr' => 'Ingénieur en voirie et réseaux divers', 'en' => 'VRD engineer'],
            ],

            // ==================== LOGISTIQUE & TRANSPORT ====================
            'warehouse-logistics' => [
                ['fr' => 'Préparateur de commandes', 'en' => 'Order picker'],
                ['fr' => 'Cariste', 'en' => 'Forklift operator'],
                ['fr' => 'Magasinier', 'en' => 'Warehouse clerk'],
                ['fr' => 'Agent de quai', 'en' => 'Dock worker'],
                ['fr' => 'Gestionnaire d\'entrepôt', 'en' => 'Warehouse manager'],
                ['fr' => 'Responsable logistique', 'en' => 'Logistics manager'],
                ['fr' => 'Agent de réception / expédition', 'en' => 'Receiving / shipping clerk'],
                ['fr' => 'Opérateur de chariot élévateur', 'en' => 'Forklift driver'],
                ['fr' => 'Technicien WMS', 'en' => 'WMS technician'],
                ['fr' => 'Coordinateur logistique', 'en' => 'Logistics coordinator'],
                ['fr' => 'Emballage professionnel', 'en' => 'Professional packer'],
                ['fr' => 'Gestionnaire de stocks', 'en' => 'Stock controller'],
                ['fr' => 'Opérateur de scan logistique', 'en' => 'Logistics scan operator'],
                ['fr' => 'Agent de cross-docking', 'en' => 'Cross-docking agent'],
                ['fr' => 'Préparateur de kits', 'en' => 'Kit assembly worker'],
            ],
            'transport-delivery' => [
                ['fr' => 'Livreur', 'en' => 'Delivery driver'],
                ['fr' => 'Chauffeur-livreur', 'en' => 'Delivery courier'],
                ['fr' => 'Conducteur de camion', 'en' => 'Truck driver'],
                ['fr' => 'Routier', 'en' => 'Long-haul trucker'],
                ['fr' => 'Conducteur de camion frigorifique', 'en' => 'Refrigerated truck driver'],
                ['fr' => 'Conducteur de semi-remorque', 'en' => 'Semi-trailer driver'],
                ['fr' => 'Chauffeur de VUL', 'en' => 'Van driver'],
                ['fr' => 'Responsable de tournées', 'en' => 'Route planner'],
                ['fr' => 'Déménageur', 'en' => 'Mover'],
                ['fr' => 'Conducteur de camion-citerne', 'en' => 'Tanker truck driver'],
                ['fr' => 'Conducteur de benne à ordures', 'en' => 'Bin lorry driver'],
                ['fr' => 'Conducteur de camion porte-voitures', 'en' => 'Car carrier driver'],
                ['fr' => 'Chauffeur de transport de personnes à mobilité réduite', 'en' => 'Disabled transport driver'],
                ['fr' => 'Livreur express', 'en' => 'Express delivery courier'],
                ['fr' => 'Organisateur de déménagement', 'en' => 'Move organizer'],
            ],
            'heavy-vehicle-taxi-driving' => [
                ['fr' => 'Chauffeur de taxi', 'en' => 'Taxi driver'],
                ['fr' => 'Chauffeur VTC', 'en' => 'Ride-hail driver'],
                ['fr' => 'Conducteur de bus', 'en' => 'Bus driver'],
                ['fr' => 'Conducteur de car', 'en' => 'Coach driver'],
                ['fr' => 'Conducteur de poids lourd', 'en' => 'Heavy goods vehicle driver'],
                ['fr' => 'Conducteur d\'autocar', 'en' => 'Motorcoach driver'],
                ['fr' => 'Conducteur de tramway', 'en' => 'Tram driver'],
                ['fr' => 'Conducteur de métro', 'en' => 'Subway driver'],
                ['fr' => 'Conducteur de train', 'en' => 'Train driver'],
                ['fr' => 'Mototaxi', 'en' => 'Motorcycle taxi driver'],
            ],
            'couriers-motorcycle-bike' => [
                ['fr' => 'Livreur à moto', 'en' => 'Motorcycle courier'],
                ['fr' => 'Livreur à vélo', 'en' => 'Bike courier'],
                ['fr' => 'Coursier', 'en' => 'Messenger'],
                ['fr' => 'Livreur de repas (UberEats, Deliveroo)', 'en' => 'Food delivery rider'],
            ],
            'maritime-port-transport' => [
                ['fr' => 'Marin', 'en' => 'Sailor'],
                ['fr' => 'Matelot', 'en' => 'Deckhand'],
                ['fr' => 'Capitaine', 'en' => 'Captain'],
                ['fr' => 'Officier de pont', 'en' => 'Deck officer'],
                ['fr' => 'Docker', 'en' => 'Docker'],
                ['fr' => 'Grutier portuaire', 'en' => 'Port crane operator'],
                ['fr' => 'Agent de manutention', 'en' => 'Stevedore'],
                ['fr' => 'Technicien de maintenance portuaire', 'en' => 'Port maintenance technician'],
                ['fr' => 'Pilote maritime', 'en' => 'Maritime pilot'],
                ['fr' => 'Agent de transit / Transitaire', 'en' => 'Freight forwarder'],
                ['fr' => 'Déclarant en douane', 'en' => 'Customs declarant'],
                ['fr' => 'Courtier en fret', 'en' => 'Freight broker'],
                ['fr' => 'Agent de fret maritime', 'en' => 'Sea freight agent'],
                ['fr' => 'Mécanicien naval', 'en' => 'Marine mechanic'],
                ['fr' => 'Électricien naval', 'en' => 'Marine electrician'],
                ['fr' => 'Soudeur naval', 'en' => 'Marine welder'],
                ['fr' => 'Peintre naval', 'en' => 'Marine painter'],
                ['fr' => 'Gréeur', 'en' => 'Rigger'],
                ['fr' => 'Arrimeur', 'en' => 'Lashing worker / Cargo securer'],
                ['fr' => 'Conducteur de bateau de transport fluvial', 'en' => 'Barge driver'],
                ['fr' => 'Pilote de bateau de plaisance', 'en' => 'Pleasure boat pilot'],
                ['fr' => 'Capitaine de navire de commerce', 'en' => 'Merchant navy captain'],
                ['fr' => 'Officier mécanicien naval', 'en' => 'Marine engineering officer'],
                ['fr' => 'Matelot de pont', 'en' => 'Able seaman'],
            ],
            'aviation-airport-services' => [
                ['fr' => 'Pilote de ligne', 'en' => 'Airline pilot'],
                ['fr' => 'Hôtesse de l\'air / Steward', 'en' => 'Flight attendant'],
                ['fr' => 'Agent d\'escale', 'en' => 'Ground handling agent'],
                ['fr' => 'Contrôleur aérien', 'en' => 'Air traffic controller'],
                ['fr' => 'Mécanicien aéronautique', 'en' => 'Aircraft mechanic'],
                ['fr' => 'Agent de piste', 'en' => 'Ramp agent'],
                ['fr' => 'Agent de sécurité aéroportuaire', 'en' => 'Airport security agent'],
                ['fr' => 'Technicien de maintenance aéronautique', 'en' => 'Aeronautical maintenance technician'],
                ['fr' => 'Pilote d\'hélicoptère', 'en' => 'Helicopter pilot'],
                ['fr' => 'Agent de fret aérien', 'en' => 'Air freight agent'],
                ['fr' => 'Agent d\'escale fret', 'en' => 'Cargo ground handling agent'],
                ['fr' => 'Personnel de cabine supplémentaire', 'en' => 'Cabin crew trainee'],
                ['fr' => 'Dispatcher aérien', 'en' => 'Flight dispatcher'],
                ['fr' => 'Mécanicien de cellule aéronautique', 'en' => 'Airframe mechanic'],
                ['fr' => 'Mécanicien avionique', 'en' => 'Avionics technician'],
                ['fr' => 'Agent de nettoyage aéronef', 'en' => 'Aircraft cleaner'],
                ['fr' => 'Agent de ravitaillement en carburant', 'en' => 'Aircraft refueler'],
            ],
            'transport-mobility' => [
                ['fr' => 'Agent de mobilité', 'en' => 'Mobility agent'],
                ['fr' => 'Planificateur de transport', 'en' => 'Transport planner'],
                ['fr' => 'Gestionnaire de flotte', 'en' => 'Fleet manager'],
                ['fr' => 'Agent de circulation', 'en' => 'Traffic warden / Traffic controller'],
                ['fr' => 'Exploitant de systèmes de transport', 'en' => 'Transport system operator'],
                ['fr' => 'Chargé de mobilité durable', 'en' => 'Sustainable mobility officer'],
                ['fr' => 'Agent d\'information voyageurs', 'en' => 'Passenger information agent'],
            ],

            // ==================== SANTÉ & SOCIAL ====================
            'medical-paramedical' => [
                ['fr' => 'Infirmier(ère)', 'en' => 'Nurse'],
                ['fr' => 'Aide-soignant(e)', 'en' => 'Nursing assistant'],
                ['fr' => 'Technicien de laboratoire', 'en' => 'Laboratory technician'],
                ['fr' => 'Radiologue', 'en' => 'Radiologist'],
                ['fr' => 'Kinésithérapeute', 'en' => 'Physiotherapist'],
                ['fr' => 'Ergothérapeute', 'en' => 'Occupational therapist'],
                ['fr' => 'Manipulateur radio', 'en' => 'Radiologic technologist'],
                ['fr' => 'Médecin généraliste', 'en' => 'General practitioner'],
                ['fr' => 'Médecin spécialiste', 'en' => 'Medical specialist'],
                ['fr' => 'Chirurgien', 'en' => 'Surgeon'],
                ['fr' => 'Anesthésiste', 'en' => 'Anesthesiologist'],
                ['fr' => 'Pédiatre', 'en' => 'Pediatrician'],
                ['fr' => 'Gynécologue', 'en' => 'Gynecologist'],
                ['fr' => 'Cardiologue', 'en' => 'Cardiologist'],
                ['fr' => 'Ophtalmologiste', 'en' => 'Ophthalmologist'],
                ['fr' => 'Infirmier(e) anesthésiste', 'en' => 'Nurse anesthetist'],
                ['fr' => 'Orthophoniste', 'en' => 'Speech therapist'],
                ['fr' => 'Orthoptiste', 'en' => 'Orthoptist'],
                ['fr' => 'Diététicien(ne)', 'en' => 'Dietitian'],
                ['fr' => 'Podologue', 'en' => 'Podiatrist'],
                ['fr' => 'Préleveur médical', 'en' => 'Phlebotomist'],
                ['fr' => 'Brancardier', 'en' => 'Stretcher-bearer'],
                ['fr' => 'Biologiste médical', 'en' => 'Clinical biologist'],
                ['fr' => 'Technicien d\'anatomie pathologique', 'en' => 'Pathology technician'],
                ['fr' => 'Audioprothésiste', 'en' => 'Hearing aid specialist'],
                ['fr' => 'Opticien-lunetier', 'en' => 'Optician'],
                ['fr' => 'Prothésiste dentaire', 'en' => 'Dental prosthetist'],
                ['fr' => 'Prothésiste orthopédique', 'en' => 'Orthopedic prosthetist'],
                ['fr' => 'Podo-orthésiste', 'en' => 'Podiatrist-orthotist'],
                ['fr' => 'Orthésiste', 'en' => 'Orthotist'],
                ['fr' => 'Préparateur en pharmacie', 'en' => 'Pharmacy assistant'],
                ['fr' => 'Neurologue', 'en' => 'Neurologist'],
                ['fr' => 'Dermatologue', 'en' => 'Dermatologist'],
                ['fr' => 'ORL (Oto-rhino-laryngologiste)', 'en' => 'ENT specialist'],
                ['fr' => 'Urologue', 'en' => 'Urologist'],
                ['fr' => 'Pneumologue', 'en' => 'Pulmonologist'],
                ['fr' => 'Rhumatologue', 'en' => 'Rheumatologist'],
                ['fr' => 'Endocrinologue', 'en' => 'Endocrinologist'],
                ['fr' => 'Oncologue', 'en' => 'Oncologist'],
                ['fr' => 'Médecin légiste', 'en' => 'Forensic pathologist'],
                ['fr' => 'Médecin du travail', 'en' => 'Occupational physician'],
                ['fr' => 'Médecin du sport', 'en' => 'Sports physician'],
                ['fr' => 'Médecin scolaire', 'en' => 'School physician'],
                ['fr' => 'Infirmier du travail', 'en' => 'Occupational health nurse'],
                ['fr' => 'Infirmier scolaire', 'en' => 'School nurse'],
                ['fr' => 'Vétérinaire', 'en' => 'Veterinarian'],
                ['fr' => 'Assistant vétérinaire', 'en' => 'Veterinary assistant'],
                ['fr' => 'Infirmier de secteur psychiatrique', 'en' => 'Psychiatric nurse'],
                ['fr' => 'Ergonome', 'en' => 'Ergonomist'],
            ],
            'personal-care-assistance' => [
                ['fr' => 'Aide à domicile', 'en' => 'Home care aide'],
                ['fr' => 'Auxiliaire de vie', 'en' => 'Care assistant'],
                ['fr' => 'Accompagnant éducatif', 'en' => 'Educational care worker'],
                ['fr' => 'Aide ménagère', 'en' => 'Housekeeper'],
                ['fr' => 'Téléassistant(e)', 'en' => 'Telecare operator'],
                ['fr' => 'Assistant de soins en gérontologie', 'en' => 'Geriatric care assistant'],
                ['fr' => 'Auxiliaire de puériculture', 'en' => 'Childcare assistant'],
                ['fr' => 'Éducateur de jeunes enfants', 'en' => 'Early childhood educator'],
                ['fr' => 'Accompagnateur de personnes handicapées', 'en' => 'Disability support worker'],
                ['fr' => 'Interprète en langue des signes', 'en' => 'Sign language interpreter'],
                ['fr' => 'Auxiliaire de vie sociale', 'en' => 'Social care assistant'],
            ],
            'mental-health-wellness' => [
                ['fr' => 'Psychologue', 'en' => 'Psychologist'],
                ['fr' => 'Conseiller en insertion', 'en' => 'Integration counselor'],
                ['fr' => 'Psychiatre', 'en' => 'Psychiatrist'],
                ['fr' => 'Psychothérapeute', 'en' => 'Psychotherapist'],
                ['fr' => 'Coach en développement personnel', 'en' => 'Personal development coach'],
                ['fr' => 'Médiateur social', 'en' => 'Social mediator'],
                ['fr' => 'Éducateur spécialisé', 'en' => 'Special educator'],
                ['fr' => 'Conseiller conjugal et familial', 'en' => 'Family counselor'],
                ['fr' => 'Médiateur familial', 'en' => 'Family mediator'],
                ['fr' => 'Éducateur de rue', 'en' => 'Street educator'],
                ['fr' => 'Art-thérapeute', 'en' => 'Art therapist'],
                ['fr' => 'Musicothérapeute', 'en' => 'Music therapist'],
            ],
            'healthcare-medical' => [
                ['fr' => 'Médecin généraliste', 'en' => 'General practitioner'],
                ['fr' => 'Médecin spécialiste', 'en' => 'Specialist doctor'],
                ['fr' => 'Chirurgien', 'en' => 'Surgeon'],
                ['fr' => 'Sage-femme', 'en' => 'Midwife'],
                ['fr' => 'Pharmacien', 'en' => 'Pharmacist'],
                ['fr' => 'Dentiste', 'en' => 'Dentist'],
                ['fr' => 'Pharmacien d\'officine', 'en' => 'Community pharmacist'],
                ['fr' => 'Pharmacien hospitalier', 'en' => 'Hospital pharmacist'],
                ['fr' => 'Orthodontiste', 'en' => 'Orthodontist'],
                ['fr' => 'Chirurgien-dentiste', 'en' => 'Dental surgeon'],
                ['fr' => 'Médecin urgentiste', 'en' => 'Emergency physician'],
                ['fr' => 'Radiologue thérapeute', 'en' => 'Therapeutic radiologist'],
                ['fr' => 'Médecin interniste', 'en' => 'Internist'],
                ['fr' => 'Gériatre', 'en' => 'Geriatrician'],
                ['fr' => 'Néphrologue', 'en' => 'Nephrologist'],
                ['fr' => 'Hématologue', 'en' => 'Hematologist'],
                ['fr' => 'Gastro-entérologue', 'en' => 'Gastroenterologist'],
                ['fr' => 'Rhumatologue', 'en' => 'Rheumatologist'],
                ['fr' => 'Addictologue', 'en' => 'Addiction specialist'],
            ],
            'personal-care-home-services' => [
                ['fr' => 'Aide ménager(e)', 'en' => 'Domestic helper'],
                ['fr' => 'Employé de maison', 'en' => 'Domestic worker'],
                ['fr' => 'Garde d\'enfant', 'en' => 'Childminder'],
                ['fr' => 'Assistant familial', 'en' => 'Foster care worker'],
                ['fr' => 'Agent de services à la personne', 'en' => 'Personal service agent'],
                ['fr' => 'Nounou / Garde d\'enfants à domicile', 'en' => 'Nanny'],
                ['fr' => 'Assistant maternel', 'en' => 'Childminder'],
                ['fr' => 'Femme de ménage à temps partiel', 'en' => 'Part-time housekeeper'],
                ['fr' => 'Repasseur(se)', 'en' => 'Ironer'],
                ['fr' => 'Cuisinier à domicile', 'en' => 'Private cook'],
                ['fr' => 'Jardinier de particulier', 'en' => 'Private gardener'],
                ['fr' => 'Garde d\'animaux / Pet-sitter', 'en' => 'Pet sitter'],
            ],

            // ==================== HÔTELLERIE & RESTAURATION ====================
            'catering-culinary' => [
                ['fr' => 'Cuisinier(ère)', 'en' => 'Cook'],
                ['fr' => 'Commis de cuisine', 'en' => 'Kitchen assistant'],
                ['fr' => 'Chef de partie', 'en' => 'Line cook'],

                ['fr' => 'Traiteur', 'en' => 'Caterer'],
                ['fr' => 'Boucher', 'en' => 'Butcher'],
                ['fr' => 'Charcutier', 'en' => 'Charcutier / Delicatessen maker'],
                ['fr' => 'Poissonnier', 'en' => 'Fishmonger'],
                ['fr' => 'Chocolatier', 'en' => 'Chocolatier'],
                ['fr' => 'Confiseur', 'en' => 'Confectioner'],
                ['fr' => 'Glacier', 'en' => 'Ice cream maker'],
                ['fr' => 'Crêpier', 'en' => 'Crêpe maker'],
                ['fr' => 'Grillardin', 'en' => 'Grill cook'],
                ['fr' => 'Poissonnier-traiteur', 'en' => 'Fish caterer'],
                ['fr' => 'Torréfacteur', 'en' => 'Coffee roaster'],
                ['fr' => 'Décorateur de gâteaux', 'en' => 'Cake decorator'],
                ['fr' => 'Cuisinier en offshore', 'en' => 'Offshore cook'],
                ['fr' => 'Cuisinier de navire', 'en' => 'Ship\'s cook'],
                ['fr' => 'Préparateur en charcuterie', 'en' => 'Charcuterie preparer'],
            ],
            'waiting-bar-service' => [
                ['fr' => 'Serveur(se)', 'en' => 'Waiter/waitress'],
                ['fr' => 'Barman / Barmaid', 'en' => 'Bartender'],
                ['fr' => 'Sommelier(ère)', 'en' => 'Sommelier'],
                ['fr' => 'Chef de rang', 'en' => 'Head waiter'],
                ['fr' => 'Aide-barman', 'en' => 'Barback'],
                ['fr' => 'Caféier', 'en' => 'Barista'],
                ['fr' => 'Plongeur', 'en' => 'Dishwasher'],
['fr' => 'Débarrasseur', 'en' => 'Busboy'],
['fr' => 'Runner', 'en' => 'Food runner'],
['fr' => 'Maître d\'hôtel', 'en' => 'Maitre d\''],
['fr' => 'Caviste', 'en' => 'Wine advisor / Sommelier (retail)'],
['fr' => 'Mixologue', 'en' => 'Mixologist'],
['fr' => 'Shooter de barman ambulant', 'en' => 'Mobile bartender'],
            ],
            'hotel-accommodation' => [
                ['fr' => 'Réceptionniste hôtelier', 'en' => 'Hotel receptionist'],
                ['fr' => 'Femme / Valet de chambre', 'en' => 'Housekeeper'],
                ['fr' => 'Gouvernant(e) d\'étages', 'en' => 'Floor supervisor'],
                ['fr' => 'Concierge', 'en' => 'Concierge'],
                ['fr' => 'Responsable d\'hébergement', 'en' => 'Accommodation manager'],
                ['fr' => 'Veilleur de nuit', 'en' => 'Night watchman'],
                ['fr' => 'Directeur d\'hôtel', 'en' => 'Hotel director / General manager'],
['fr' => 'Bagagiste', 'en' => 'Bellboy / Porter'],
['fr' => 'Standardiste hôtelier', 'en' => 'Hotel switchboard operator'],
['fr' => 'Chef réceptionniste', 'en' => 'Head receptionist'],
['fr' => 'Concierge de nuit', 'en' => 'Night concierge'],
['fr' => 'Gouvernant(e) générale', 'en' => 'Executive housekeeper'],
['fr' => 'Lingerie / Laveuse', 'en' => 'Laundry worker'],
['fr' => 'Technicien de blanchisserie', 'en' => 'Laundry technician'],
['fr' => 'Gérant d\'auberge / de gîte', 'en' => 'Innkeeper / Guesthouse manager'],
['fr' => 'Gérant de camping', 'en' => 'Campsite manager'],
            ],
            'cleaning-maintenance' => [
                ['fr' => 'Agent d\'entretien', 'en' => 'Cleaning agent'],
                ['fr' => 'Agent de propreté', 'en' => 'Sanitation worker'],
                ['fr' => 'Technicien de maintenance', 'en' => 'Maintenance technician'],
                ['fr' => 'Agent de nettoyage industriel', 'en' => 'Industrial cleaner'],
                ['fr' => 'Responsable d\'entretien', 'en' => 'Cleaning supervisor'],
                ['fr' => 'Laveur de vitres', 'en' => 'Window cleaner'],
['fr' => 'Nettoyeur de façades', 'en' => 'Facade cleaner'],
['fr' => 'Désinfecteur', 'en' => 'Disinfector'],
['fr' => 'Exterminateur / Technicien de lutte antiparasitaire', 'en' => 'Pest controller'],
['fr' => 'Nettoyeur de fin de chantier', 'en' => 'Post-construction cleaner'],
['fr' => 'Technicien de nettoyage industriel', 'en' => 'Industrial cleaning technician'],
['fr' => 'Nettoyeur de cuves', 'en' => 'Tank cleaner'],
['fr' => 'Décapage de sols', 'en' => 'Floor stripping technician'],
            ],
            'cleaning-hygiene' => [
                ['fr' => 'Agent de nettoyage', 'en' => 'Cleaner'],
                ['fr' => 'Technicien de surface', 'en' => 'Surface technician'],
                ['fr' => 'Employé d\'entretien', 'en' => 'Maintenance employee'],
                ['fr' => 'Agent d\'hygiène', 'en' => 'Hygiene agent'],
                ['fr' => 'Agent de bio-nettoyage', 'en' => 'Bio-cleaning agent'],
['fr' => 'Agent d\'hygiène hospitalière', 'en' => 'Hospital hygiene agent'],
['fr' => 'Technicien de stérilisation', 'en' => 'Sterilization technician'],
            ],
            'tourism-hospitality' => [
                ['fr' => 'Guide touristique', 'en' => 'Tour guide'],
                ['fr' => 'Animateur touristique', 'en' => 'Tourism animator'],
                ['fr' => 'Conseiller en séjour', 'en' => 'Travel advisor'],
                ['fr' => 'Agent de voyage', 'en' => 'Travel agent'],
                ['fr' => 'Responsable de site touristique', 'en' => 'Tourist site manager'],
                ['fr' => 'Interprète guide', 'en' => 'Guide interpreter'],
                ['fr' => 'Guide de montagne', 'en' => 'Mountain guide'],
['fr' => 'Accompagnateur en moyenne montagne', 'en' => 'Mid-mountain guide'],
['fr' => 'Moniteur de randonnée', 'en' => 'Hiking guide'],
['fr' => 'Guide naturaliste', 'en' => 'Nature guide'],
['fr' => 'Animateur de croisière', 'en' => 'Cruise animator'],
['fr' => 'Directeur d\'agence de voyage', 'en' => 'Travel agency manager'],
['fr' => 'Conseiller en voyages de luxe', 'en' => 'Luxury travel advisor'],
['fr' => 'Guide de ville', 'en' => 'City guide'],
            ],
            'food-beverage' => [
                ['fr' => 'Serveur en restauration rapide', 'en' => 'Fast food server'],
                ['fr' => 'Cuisinier de fast-food', 'en' => 'Fast food cook'],
                ['fr' => 'Barista', 'en' => 'Barista'],
                ['fr' => 'Préparateur de commandes en restauration', 'en' => 'Food delivery prep'],
            ],

            // ==================== RELATION CLIENT & ADMINISTRATIF ====================
            'customer-service-call-center' => [
                ['fr' => 'Conseiller clientèle', 'en' => 'Customer service advisor'],
                ['fr' => 'Téléconseiller', 'en' => 'Call center agent'],
                ['fr' => 'Chargé de relation client', 'en' => 'Customer relationship manager'],
                ['fr' => 'Agent de centre d\'appels', 'en' => 'Call center operator'],
                ['fr' => 'Chargé de satisfaction client', 'en' => 'Customer satisfaction officer'],
                ['fr' => 'Superviseur de plateau', 'en' => 'Floor supervisor'],
                ['fr' => 'Téléconseiller technique', 'en' => 'Technical support agent'],
['fr' => 'Téléconseiller après-vente', 'en' => 'After-sales phone advisor'],
['fr' => 'Gestionnaire de réclamations', 'en' => 'Complaints handler'],
['fr' => 'Formateur de plateau', 'en' => 'Call center trainer'],
['fr' => 'Qualiticien (centre d\'appels)', 'en' => 'Call center quality analyst'],
            ],
            'administration-management' => [
                ['fr' => 'Assistant(e) administratif(ve)', 'en' => 'Administrative assistant'],
                ['fr' => 'Comptable', 'en' => 'Accountant'],
                ['fr' => 'Gestionnaire de paie', 'en' => 'Payroll manager'],
                ['fr' => 'Chargé(e) de projet', 'en' => 'Project officer'],
                ['fr' => 'Secrétaire', 'en' => 'Secretary'],
                ['fr' => 'Chef de projet', 'en' => 'Project manager'],
                ['fr' => 'Contrôleur de gestion', 'en' => 'Management controller'],
                ['fr' => 'Responsable administratif', 'en' => 'Administrative manager'],
                ['fr' => 'Assistante de direction', 'en' => 'Executive assistant'],
['fr' => 'Secrétaire de direction', 'en' => 'Executive secretary'],
['fr' => 'Standardiste', 'en' => 'Switchboard operator'],
['fr' => 'Saisisseur de données', 'en' => 'Data entry clerk'],
['fr' => 'Archiviste', 'en' => 'Archivist'],
['fr' => 'Documentaliste', 'en' => 'Documentalist'],
['fr' => 'Gestionnaire de contrats', 'en' => 'Contract manager'],
['fr' => 'Responsable de bureau', 'en' => 'Office manager'],
['fr' => 'Auditeur interne', 'en' => 'Internal auditor'],
['fr' => 'Consultant en organisation', 'en' => 'Organization consultant'],
['fr' => 'Gestionnaire de fournisseurs', 'en' => 'Supplier manager'],
['fr' => 'Acheteur', 'en' => 'Buyer / Purchaser'],
['fr' => 'Acheteur public', 'en' => 'Public buyer'],
['fr' => 'Approvisionneur', 'en' => 'Supply officer'],
['fr' => 'Responsable des achats', 'en' => 'Purchasing manager'],
            ],
            'human-resources' => [
                ['fr' => 'Chargé(e) de recrutement', 'en' => 'Recruitment officer'],
                ['fr' => 'Gestionnaire RH', 'en' => 'HR manager'],
                ['fr' => 'Responsable formation', 'en' => 'Training manager'],
                ['fr' => 'Chargé de paie', 'en' => 'Payroll administrator'],
                ['fr' => 'Chargé de relations sociales', 'en' => 'Employee relations officer'],
                ['fr' => 'Directeur RH', 'en' => 'HR director'],
['fr' => 'Chargé d\'administration du personnel', 'en' => 'Personnel administration officer'],
['fr' => 'Responsable paie', 'en' => 'Payroll manager'],
['fr' => 'Chargé de développement RH', 'en' => 'HR development officer'],
['fr' => 'Psychologue du travail', 'en' => 'Occupational psychologist'],
['fr' => 'Chargé de mobilité internationale', 'en' => 'International mobility officer'],
['fr' => 'Assistant RH', 'en' => 'HR assistant'],
            ],
            'legal-services' => [
                ['fr' => 'Juriste', 'en' => 'Legal counsel'],
                ['fr' => 'Assistant(e) juridique', 'en' => 'Legal assistant'],
                ['fr' => 'Avocat', 'en' => 'Lawyer'],
                ['fr' => 'Notaire', 'en' => 'Notary'],
                ['fr' => 'Clerc de notaire', 'en' => 'Notary clerk'],
                ['fr' => 'Conseil juridique', 'en' => 'Legal advisor'],
                ['fr' => 'Huissier de justice', 'en' => 'Bailiff'],
['fr' => 'Commissaire-priseur', 'en' => 'Auctioneer'],
['fr' => 'Greffier', 'en' => 'Court clerk'],
['fr' => 'Médiateur judiciaire', 'en' => 'Judicial mediator'],
['fr' => 'Conciliateur de justice', 'en' => 'Justice conciliator'],
['fr' => 'Expert judiciaire', 'en' => 'Court-appointed expert'],
['fr' => 'Traducteur assermenté', 'en' => 'Sworn translator'],
['fr' => 'Avocat spécialisé', 'en' => 'Specialist lawyer'],
['fr' => 'Avocat d\'affaires', 'en' => 'Corporate lawyer'],
['fr' => 'Juriste d\'entreprise', 'en' => 'In-house counsel'],
['fr' => 'Responsable des affaires réglementaires', 'en' => 'Regulatory affairs manager'],
            ],
            'banking-finance' => [
                ['fr' => 'Conseiller bancaire', 'en' => 'Bank advisor'],
                ['fr' => 'Analyste financier', 'en' => 'Financial analyst'],
                ['fr' => 'Chargé de clientèle bancaire', 'en' => 'Bank customer service officer'],
                ['fr' => 'Gestionnaire de comptes', 'en' => 'Account manager'],
                ['fr' => 'Trésorier', 'en' => 'Treasurer'],
                ['fr' => 'Auditeur financier', 'en' => 'Financial auditor'],
                ['fr' => 'Expert-comptable', 'en' => 'Certified public accountant'],
['fr' => 'Aide-comptable', 'en' => 'Accounting assistant'],
['fr' => 'Comptable unique', 'en' => 'Sole accountant'],
['fr' => 'Conseiller fiscal', 'en' => 'Tax advisor'],
['fr' => 'Agent de recouvrement', 'en' => 'Debt collector'],
['fr' => 'Courtier en bourse', 'en' => 'Stockbroker'],
['fr' => 'Gestionnaire d\'actifs', 'en' => 'Asset manager'],
['fr' => 'Analyste de crédit', 'en' => 'Credit analyst'],
['fr' => 'Conseiller en investissement', 'en' => 'Investment advisor'],
['fr' => 'Agent de change', 'en' => 'Floor trader'],
['fr' => 'Contrôleur financier', 'en' => 'Financial controller'],
['fr' => 'Gestionnaire de crédits', 'en' => 'Credit manager'],
            ],
            'public-services-administration' => [
                ['fr' => 'Fonctionnaire', 'en' => 'Civil servant'],
                ['fr' => 'Agent administratif de mairie', 'en' => 'Municipal administrative officer'],
                ['fr' => 'Agent de service public', 'en' => 'Public service agent'],
                ['fr' => 'Secrétaire de mairie', 'en' => 'Town clerk'],
                ['fr' => 'Inspecteur des impôts', 'en' => 'Tax inspector'],
['fr' => 'Agent des impôts', 'en' => 'Tax officer'],
['fr' => 'Inspecteur du travail', 'en' => 'Labor inspector'],
['fr' => 'Agent de la Caisse d\'assurance maladie', 'en' => 'Health insurance officer'],
['fr' => 'Agent de la Caisse d\'allocations familiales', 'en' => 'Family allowance officer'],
['fr' => 'Agent de Pôle Emploi / Service public de l\'emploi', 'en' => 'Public employment service agent'],
['fr' => 'Éducateur de la protection judiciaire de la jeunesse', 'en' => 'Youth justice educator'],
['fr' => 'Agent de la protection civile', 'en' => 'Civil protection agent'],
['fr' => 'Agent des eaux et forêts', 'en' => 'Water and forestry officer'],
['fr' => 'Diplomate', 'en' => 'Diplomat'],
['fr' => 'Agent consulaire', 'en' => 'Consular officer'],
['fr' => 'Juge administratif', 'en' => 'Administrative judge'],
['fr' => 'Juge judiciaire', 'en' => 'Judicial judge'],
['fr' => 'Procureur', 'en' => 'Prosecutor'],
['fr' => 'Policier', 'en' => 'Police officer'],
['fr' => 'Gendarme', 'en' => 'Gendarme'],
['fr' => 'Commissaire de police', 'en' => 'Police commissioner'],
['fr' => 'Gardien de prison / Surveillant pénitentiaire', 'en' => 'Prison guard'],
            ],
            'real-estate-property-management' => [
                ['fr' => 'Agent immobilier', 'en' => 'Real estate agent'],
                ['fr' => 'Gestionnaire de copropriété', 'en' => 'Property manager'],
                ['fr' => 'Syndic', 'en' => 'Trustee'],
                ['fr' => 'Chargé de location', 'en' => 'Rental manager'],
                ['fr' => 'Négociateur immobilier', 'en' => 'Real estate negotiator'],
                ['fr' => 'Expert en évaluation immobilière', 'en' => 'Real estate appraiser'],
['fr' => 'Aménageur d\'intérieur', 'en' => 'Interior designer'],
['fr' => 'Home stager', 'en' => 'Home stager'],
['fr' => 'Agent de location saisonnière', 'en' => 'Seasonal rental agent'],
['fr' => 'Gérant de résidence', 'en' => 'Residence manager'],
['fr' => 'Conseiller en investissement locatif', 'en' => 'Rental investment advisor'],
['fr' => 'Promoteur immobilier', 'en' => 'Real estate developer'],
['fr' => 'Lotisseur', 'en' => 'Land developer'],
['fr' => 'Géomètre-expert', 'en' => 'Expert surveyor'],
            ],

            // ==================== MÉDIAS & COMMUNICATION ====================
            'media-journalism' => [
                ['fr' => 'Journaliste', 'en' => 'Journalist'],
                ['fr' => 'Rédacteur web', 'en' => 'Web writer'],
                ['fr' => 'Reporter', 'en' => 'Reporter'],
                ['fr' => 'Chef de rédaction', 'en' => 'Editor-in-chief'],
                ['fr' => 'Chargé de communication', 'en' => 'Communications officer'],
                ['fr' => 'Community manager', 'en' => 'Community manager'],
                ['fr' => 'Traffic manager', 'en' => 'Traffic manager'],
                ['fr' => 'Photographe de presse', 'en' => 'Press photographer'],
['fr' => 'Journaliste reporter d\'images', 'en' => 'Video journalist'],
['fr' => 'Chroniqueur', 'en' => 'Columnist'],
['fr' => 'Éditorialiste', 'en' => 'Editorialist'],
['fr' => 'Rédacteur en chef adjoint', 'en' => 'Deputy editor-in-chief'],
['fr' => 'Correcteur', 'en' => 'Proofreader'],
['fr' => 'Traducteur', 'en' => 'Translator'],
['fr' => 'Interprète de conférence', 'en' => 'Conference interpreter'],
['fr' => 'Animateur radio', 'en' => 'Radio host'],
['fr' => 'Présentateur télé', 'en' => 'TV presenter'],
['fr' => 'Journaliste d\'investigation', 'en' => 'Investigative journalist'],
['fr' => 'Rédacteur technique', 'en' => 'Technical writer'],
['fr' => 'Webmaster', 'en' => 'Webmaster'],
            ],
            'marketing-advertising' => [
                ['fr' => 'Chargé(e) de marketing', 'en' => 'Marketing officer'],
                ['fr' => 'Community manager', 'en' => 'Community manager'],
                ['fr' => 'Traffic manager', 'en' => 'Traffic manager'],
                ['fr' => 'Chef de produit', 'en' => 'Product manager'],
                ['fr' => 'Responsable marketing digital', 'en' => 'Digital marketing manager'],
                ['fr' => 'Growth hacker', 'en' => 'Growth hacker'],
                ['fr' => 'Brand manager', 'en' => 'Brand manager'],
                ['fr' => 'Copywriter', 'en' => 'Copywriter'],
['fr' => 'Concepteur-rédacteur', 'en' => 'Creative copywriter'],
['fr' => 'Directeur de création', 'en' => 'Creative director'],
['fr' => 'Planneur stratégique', 'en' => 'Strategic planner'],
['fr' => 'Chef de publicité', 'en' => 'Advertising manager'],
['fr' => 'Afficheur', 'en' => 'Poster / billboard installer'],
['fr' => 'Distributeurs de tracts', 'en' => 'Flyer distributor'],
['fr' => 'Chargé de relations publiques', 'en' => 'PR officer'],
['fr' => 'Attaché de presse', 'en' => 'Press officer'],
['fr' => 'Influenceur', 'en' => 'Influencer'],
['fr' => 'Blogueur', 'en' => 'Blogger'],
['fr' => 'Vlogueur / Youtuber', 'en' => 'Vlogger / YouTuber'],
['fr' => 'Podcasteur', 'en' => 'Podcaster'],
['fr' => 'Spécialiste réseaux sociaux', 'en' => 'Social media specialist'],
['fr' => 'Référenceur SEO', 'en' => 'SEO specialist'],
['fr' => 'Spécialiste SEM / Google Ads', 'en' => 'SEM specialist'],
['fr' => 'Affiliate marketer', 'en' => 'Affiliate marketer'],
['fr' => 'Directeur marketing', 'en' => 'Chief marketing officer'],
['fr' => 'Chargé d\'études de marché', 'en' => 'Market researcher'],
            ],
            'design-creative' => [
                ['fr' => 'Graphiste', 'en' => 'Graphic designer'],
                ['fr' => 'Designer UI/UX', 'en' => 'UI/UX designer'],
                ['fr' => 'Illustrateur', 'en' => 'Illustrator'],
                ['fr' => 'Directeur artistique', 'en' => 'Art director'],
                ['fr' => 'Motion designer', 'en' => 'Motion designer'],
                ['fr' => 'Designer de produit', 'en' => 'Product designer'],
                ['fr' => 'Maquettiste', 'en' => 'Layout artist'],
['fr' => 'Sérigraphe', 'en' => 'Screen printer'],
['fr' => 'Typographe', 'en' => 'Typographer'],
['fr' => 'Infographiste', 'en' => 'Infographic designer'],
['fr' => 'Créateur de logo', 'en' => 'Logo designer'],
['fr' => 'Designer d\'espace', 'en' => 'Space designer'],
['fr' => 'Designer sonore', 'en' => 'Sound designer'],
['fr' => 'UX Researcher', 'en' => 'UX researcher'],
            ],
            'photography-av' => [
                ['fr' => 'Photographe', 'en' => 'Photographer'],
                ['fr' => 'Monteur vidéo', 'en' => 'Video editor'],
                ['fr' => 'Réalisateur', 'en' => 'Director'],
                ['fr' => 'Chef opérateur', 'en' => 'Camera operator'],
                ['fr' => 'Ingénieur du son', 'en' => 'Sound engineer'],
                ['fr' => 'Coloriste', 'en' => 'Colorist'],
                ['fr' => 'Photographe de mariage', 'en' => 'Wedding photographer'],
['fr' => 'Photographe de produit', 'en' => 'Product photographer'],
['fr' => 'Photographe de mode', 'en' => 'Fashion photographer'],
['fr' => 'Photographe animalier', 'en' => 'Wildlife photographer'],
['fr' => 'Pilote de drone (photographie)', 'en' => 'Drone pilot (aerial photography)'],
['fr' => 'Monteur son', 'en' => 'Sound editor'],
['fr' => 'Bruiteur', 'en' => 'Foley artist'],
['fr' => 'Mixeur', 'en' => 'Sound mixer'],
['fr' => 'Perchman', 'en' => 'Boom operator'],
['fr' => 'Électricien de plateau', 'en' => 'Gaffer / Set electrician'],
['fr' => 'Chef électricien', 'en' => 'Chief lighting technician'],
['fr' => 'Scripte', 'en' => 'Script supervisor'],
['fr' => 'Accessoiriste', 'en' => 'Props master'],
['fr' => 'Costumier', 'en' => 'Costume designer'],
['fr' => 'Maquilleur de cinéma', 'en' => 'Film makeup artist'],
['fr' => 'Régisseur d\'antenne', 'en' => 'Broadcast manager'],
['fr' => 'Ingénieur de la diffusion', 'en' => 'Broadcast engineer'],
['fr' => 'Compositeur de musique', 'en' => 'Music composer'],
['fr' => 'Parolier', 'en' => 'Lyricist'],
            ],
            'events-entertainment' => [
                ['fr' => 'Organisateur d\'événements', 'en' => 'Event organizer'],
                ['fr' => 'Technicien événementiel', 'en' => 'Event technician'],
                ['fr' => 'Régisseur', 'en' => 'Stage manager'],
                ['fr' => 'Animateur d\'événements', 'en' => 'Event host'],
                ['fr' => 'Planner événementiel', 'en' => 'Event planner'],
                ['fr' => 'Monteur de stands', 'en' => 'Exhibition stand builder'],
['fr' => 'Décorateur événementiel', 'en' => 'Event decorator'],
['fr' => 'Technicien lumière événementiel', 'en' => 'Event lighting technician'],
['fr' => 'Technicien son événementiel', 'en' => 'Event sound technician'],
['fr' => 'Photographe d\'événement', 'en' => 'Event photographer'],
['fr' => 'Vidéaste d\'événement', 'en' => 'Event videographer'],
['fr' => 'Hôtesse d\'accueil événementiel', 'en' => 'Event hostess'],
['fr' => 'Sécuritaire événementiel', 'en' => 'Event security'],
['fr' => 'Responsable de catering événementiel', 'en' => 'Event catering manager'],
['fr' => 'Lanceur de confettis / Effets spéciaux', 'en' => 'Special effects technician'],
            ],
            'entertainment-recreation' => [
                ['fr' => 'Animateur', 'en' => 'Entertainer'],
                ['fr' => 'Éducateur sportif', 'en' => 'Sports educator'],
                ['fr' => 'Guide d\'activités', 'en' => 'Activity guide'],
                ['fr' => 'Moniteur de sports', 'en' => 'Sports instructor'],
                ['fr' => 'Animateur périscolaire', 'en' => 'After-school animator'],
['fr' => 'Animateur en colonie de vacances', 'en' => 'Summer camp counselor'],
['fr' => 'Intervenant en milieu scolaire', 'en' => 'School activity leader'],
['fr' => 'Moniteur de voile', 'en' => 'Sailing instructor'],
['fr' => 'Moniteur de plongée', 'en' => 'Diving instructor'],
['fr' => 'Moniteur d\'équitation', 'en' => 'Horse riding instructor'],
['fr' => 'Maître-nageur sauveteur', 'en' => 'Lifeguard'],
['fr' => 'Surveillant de baignade', 'en' => 'Beach lifeguard'],
['fr' => 'Conteur', 'en' => 'Storyteller'],
            ],

            // ==================== IT & NUMÉRIQUE ====================
            'it-technology' => [
                ['fr' => 'Développeur web', 'en' => 'Web developer'],
                ['fr' => 'Développeur mobile', 'en' => 'Mobile developer'],
                ['fr' => 'Technicien support informatique', 'en' => 'IT support technician'],
                ['fr' => 'Administrateur systèmes', 'en' => 'Systems administrator'],
                ['fr' => 'Ingénieur DevOps', 'en' => 'DevOps engineer'],
                ['fr' => 'Analyste cybersécurité', 'en' => 'Cybersecurity analyst'],
                ['fr' => 'Développeur full-stack', 'en' => 'Full-stack developer'],
                ['fr' => 'Développeur front-end', 'en' => 'Front-end developer'],
                ['fr' => 'Développeur back-end', 'en' => 'Back-end developer'],
                ['fr' => 'Database administrator', 'en' => 'Database administrator'],
                ['fr' => 'Technicien d\'installation informatique', 'en' => 'IT installation technician'],
['fr' => 'Réparateur de matériel informatique', 'en' => 'Computer hardware repairer'],
['fr' => 'Dépanneur informatique', 'en' => 'IT troubleshooter'],
['fr' => 'Intégrateur web', 'en' => 'Web integrator'],
['fr' => 'Développeur PHP', 'en' => 'PHP developer'],
['fr' => 'Développeur Java', 'en' => 'Java developer'],
['fr' => 'Développeur Python', 'en' => 'Python developer'],
['fr' => 'Développeur React', 'en' => 'React developer'],
['fr' => 'Développeur Angular', 'en' => 'Angular developer'],
['fr' => 'Développeur Vue.js', 'en' => 'Vue.js developer'],
['fr' => 'Développeur Flutter', 'en' => 'Flutter developer'],
['fr' => 'Développeur iOS', 'en' => 'iOS developer'],
['fr' => 'Développeur Android', 'en' => 'Android developer'],
['fr' => 'Architecte logiciel', 'en' => 'Software architect'],
['fr' => 'Tech lead', 'en' => 'Tech lead'],
['fr' => 'Scrum master', 'en' => 'Scrum master'],
['fr' => 'Product Owner', 'en' => 'Product Owner'],
['fr' => 'Chef de projet digital', 'en' => 'Digital project manager'],
['fr' => 'Consultant SI', 'en' => 'IT consultant'],
['fr' => 'Testeur QA', 'en' => 'QA tester'],
['fr' => 'Formateur informatique', 'en' => 'IT trainer'],
['fr' => 'Vendeur en informatique', 'en' => 'IT salesperson'],
['fr' => 'Administrateur Office 365 / Google Workspace', 'en' => 'Office 365 / Google Workspace administrator'],
['fr' => 'Technicien de sauvegarde', 'en' => 'Backup technician'],
['fr' => 'Développeur low-code / no-code', 'en' => 'Low-code/no-code developer'],
['fr' => 'Consultant en transformation digitale', 'en' => 'Digital transformation consultant'],
            ],
            'digital-trades-data-cloud-cybersecurity' => [
                ['fr' => 'Administrateur systèmes', 'en' => 'Systems administrator'],
                ['fr' => 'Ingénieur DevOps', 'en' => 'DevOps engineer'],
                ['fr' => 'Analyste cybersécurité', 'en' => 'Cybersecurity analyst'],
                ['fr' => 'Data scientist', 'en' => 'Data scientist'],
                ['fr' => 'Ingénieur cloud', 'en' => 'Cloud engineer'],
                ['fr' => 'Architecte cloud', 'en' => 'Cloud architect'],
                ['fr' => 'RSSI (Responsable Sécurité SI)', 'en' => 'CISO'],
                ['fr' => 'Administrateur bases de données', 'en' => 'Database administrator'],
                ['fr' => 'Ingénieur données', 'en' => 'Data engineer'],
                ['fr' => 'Expert en protection des données', 'en' => 'Data protection expert'],
                ['fr' => 'Spécialiste en migration cloud', 'en' => 'Cloud migration specialist'],
['fr' => 'Pentester', 'en' => 'Penetration tester'],
['fr' => 'Analyste de menaces', 'en' => 'Threat analyst'],
['fr' => 'Ingénieur en forensique numérique', 'en' => 'Digital forensics engineer'],
['fr' => 'Data annotateur', 'en' => 'Data annotator / Labeler'],
['fr' => 'Analyste de données marketing', 'en' => 'Marketing data analyst'],
['fr' => 'Data steward', 'en' => 'Data steward'],
['fr' => 'Architecte de données', 'en' => 'Data architect'],
['fr' => 'Ingénieur MLOps', 'en' => 'MLOps engineer'],
            ],
            'artificial-intelligence' => [
                ['fr' => 'Ingénieur machine learning', 'en' => 'Machine learning engineer'],
                ['fr' => 'Data scientist', 'en' => 'Data scientist'],
                ['fr' => 'Ingénieur NLP', 'en' => 'NLP engineer'],
                ['fr' => 'Ingénieur en vision par ordinateur', 'en' => 'Computer vision engineer'],
                ['fr' => 'Ingénieur en IA générative', 'en' => 'Generative AI engineer'],
                ['fr' => 'Chercheur en IA', 'en' => 'AI researcher'],
                ['fr' => 'Prompt engineer', 'en' => 'Prompt engineer'],
['fr' => 'Éthicien de l\'IA', 'en' => 'AI ethicist'],
['fr' => 'Ingénieur en IA pour la santé', 'en' => 'Health AI engineer'],
['fr' => 'Ingénieur en IA pour la finance', 'en' => 'Finance AI engineer'],
['fr' => 'Annotateur de données IA', 'en' => 'AI data annotator'],
['fr' => 'Testeur d\'IA', 'en' => 'AI tester'],
['fr' => 'Product manager IA', 'en' => 'AI product manager'],
            ],
            'telecommunications' => [
                ['fr' => 'Technicien télécom', 'en' => 'Telecom technician'],
                ['fr' => 'Ingénieur réseau', 'en' => 'Network engineer'],
                ['fr' => 'Installateur fibre optique', 'en' => 'Fiber optic installer'],
                ['fr' => 'Technicien réseau', 'en' => 'Network technician'],
                ['fr' => 'Ingénieur en télécommunications', 'en' => 'Telecommunications engineer'],
                ['fr' => 'Technicien Wi-Fi', 'en' => 'Wi-Fi technician'],
                ['fr' => 'Installateur d\'antennes', 'en' => 'Antenna installer'],
                ['fr' => 'Technicien de centre de données télécom', 'en' => 'Telecom data center technician'],
                ['fr' => 'Opérateur de réseau mobile', 'en' => 'Mobile network operator'],
                ['fr' => 'Technicien de déploiement fibre', 'en' => 'Fiber deployment technician'],
                ['fr' => 'Épissuriste fibre optique', 'en' => 'Fiber optic splicer'],
            ],
            'cryptocurrency-blockchain' => [
                ['fr' => 'Développeur blockchain', 'en' => 'Blockchain developer'],
                ['fr' => 'Analyste cryptomonnaies', 'en' => 'Cryptocurrency analyst'],
                ['fr' => 'Ingénieur blockchain', 'en' => 'Blockchain engineer'],
                ['fr' => 'Smart contract developer', 'en' => 'Smart contract developer'],
                ['fr' => 'Responsable de communauté crypto', 'en' => 'Crypto community manager'],
                ['fr' => 'Auditeur de smart contracts', 'en' => 'Smart contract auditor'],
                ['fr' => 'Trader de cryptomonnaies', 'en' => 'Cryptocurrency trader'],
                ['fr' => 'Analyste on-chain', 'en' => 'On-chain analyst'],
            ],
            'vr-ar-technology' => [
                ['fr' => 'Développeur VR/AR', 'en' => 'VR/AR developer'],
                ['fr' => 'Designer 3D', 'en' => '3D designer'],
                ['fr' => 'Intégrateur Unity', 'en' => 'Unity developer'],
                ['fr' => 'Technicien en réalité virtuelle', 'en' => 'VR technician'],
                ['fr' => 'Product Owner VR/AR', 'en' => 'VR/AR product owner'],
                ['fr' => 'Développeur Unreal Engine', 'en' => 'Unreal Engine developer'],
['fr' => 'Modéliste 3D', 'en' => '3D modeler'],
['fr' => 'Animateur 3D', 'en' => '3D animator'],
['fr' => 'Concept artist VR/AR', 'en' => 'VR/AR concept artist'],
            ],
            'business-intelligence-strategic-watch' => [
                ['fr' => 'Veilleur stratégique', 'en' => 'Strategic watcher'],
                ['fr' => 'Analyste BI', 'en' => 'BI analyst'],
                ['fr' => 'Data analyst', 'en' => 'Data analyst'],
                ['fr' => 'Consommateur d\'études', 'en' => 'Market researcher'],
                ['fr' => 'Consultant BI', 'en' => 'BI consultant'],
['fr' => 'Développeur de tableaux de bord', 'en' => 'Dashboard developer'],
['fr' => 'Chargé d\'intelligence économique', 'en' => 'Economic intelligence officer'],
['fr' => 'Analyste concurrentiel', 'en' => 'Competitive intelligence analyst'],
            ],

            // ==================== AGRICULTURE & ENVIRONNEMENT ====================
            'agriculture-food' => [
                ['fr' => 'Agriculteur', 'en' => 'Farmer'],
                ['fr' => 'Éleveur', 'en' => 'Livestock farmer'],
                ['fr' => 'Ouvrier agricole', 'en' => 'Farm worker'],
                ['fr' => 'Jardinier paysagiste', 'en' => 'Landscaper gardener'],
                ['fr' => 'Maraîcher', 'en' => 'Market gardener'],
                ['fr' => 'Arboriculteur', 'en' => 'Orchardist'],
                ['fr' => 'Vigneron', 'en' => 'Winemaker'],
                ['fr' => 'Horticulteur', 'en' => 'Horticulturist'],
                ['fr' => 'Pépiniériste', 'en' => 'Nurseryman'],
                ['fr' => 'Apiculteur', 'en' => 'Beekeeper'],
                ['fr' => 'Conducteur d\'engins agricoles', 'en' => 'Agricultural machinery operator'],
['fr' => 'Pilote d\'avion agricole', 'en' => 'Agricultural pilot'],
['fr' => 'Technicien agricole', 'en' => 'Agricultural technician'],
['fr' => 'Conseiller agricole', 'en' => 'Agricultural advisor'],
['fr' => 'Agronome', 'en' => 'Agronomist'],
['fr' => 'Ingénieur agronome', 'en' => 'Agronomic engineer'],
['fr' => 'Inséminateur', 'en' => 'Artificial inseminator'],
['fr' => 'Vendeur / Cueilleur', 'en' => 'Harvester'],
['fr' => 'Ouvrier de serre', 'en' => 'Greenhouse worker'],
['fr' => 'Élagueur', 'en' => 'Tree pruner'],
['fr' => 'Jardinier d\'entretien', 'en' => 'Maintenance gardener'],
['fr' => 'Jardinier paysagiste d\'intérieur', 'en' => 'Interior landscaper'],
['fr' => 'Pépiniériste arbustif', 'en' => 'Shrub nursery worker'],
['fr' => 'Palisseur / Tailleur de vignes', 'en' => 'Vine pruner'],
['fr' => 'Tonnelier', 'en' => 'Cooper'],
            ],
            'food-processing-agribusiness' => [
                ['fr' => 'Technicien agroalimentaire', 'en' => 'Food processing technician'],
                ['fr' => 'Fromager', 'en' => 'Cheese maker'],
                ['fr' => 'Opérateur en transformation des viandes', 'en' => 'Meat processing operator'],
                ['fr' => 'Condimentaire', 'en' => 'Condiment maker'],
                ['fr' => 'Responsable qualité agroalimentaire', 'en' => 'Quality manager in agrifood'],
                ['fr' => 'Boulanger de pain de campagne', 'en' => 'Artisanal bread baker'],
                ['fr' => 'Opérateur de abattoir', 'en' => 'Slaughterhouse operator'],
                ['fr' => 'Découpeur de viandes', 'en' => 'Meat cutter'],
                ['fr' => 'Technicien de laboratoire agroalimentaire', 'en' => 'Food lab technician'],
                ['fr' => 'Ingénieur agroalimentaire', 'en' => 'Food engineer'],
                ['fr' => 'Contrôleur qualité alimentaire', 'en' => 'Food quality controller'],
                ['fr' => 'Opérateur de pasteurisation', 'en' => 'Pasteurization operator'],
                ['fr' => 'Conditionneur alimentaire', 'en' => 'Food packaging operator'],
                ['fr' => 'Affineur de fromages', 'en' => 'Cheese affineur'],
                ['fr' => 'Malteur', 'en' => 'Maltster'],
                ['fr' => 'Brasseur', 'en' => 'Brewer'],
            ],
            'fishing-aquaculture' => [
                ['fr' => 'Pêcheur', 'en' => 'Fisherman'],
                ['fr' => 'Aquaculteur', 'en' => 'Aquaculture farmer'],
                ['fr' => 'Ostréiculteur', 'en' => 'Oyster farmer'],
                ['fr' => 'Marin pêcheur', 'en' => 'Fishing boat crew'],
                ['fr' => 'Technicien de pisciculture', 'en' => 'Fish farm technician'],
                ['fr' => 'Pêcheur artisanal', 'en' => 'Artisanal fisherman'],
['fr' => 'Pêcheur en haute mer', 'en' => 'Deep-sea fisherman'],
['fr' => 'Patron de pêche', 'en' => 'Fishing boat captain'],
['fr' => 'Mareyeur', 'en' => 'Fish merchant'],
['fr' => 'Mytiliculteur', 'en' => 'Mussel farmer'],
['fr' => 'Conchyliculteur', 'en' => 'Shellfish farmer'],
['fr' => 'Pisciculteur d\'eau douce', 'en' => 'Freshwater fish farmer'],
['fr' => 'Écloserie (aquaculture)', 'en' => 'Hatchery worker'],
            ],
            'environment-sustainability' => [
                ['fr' => 'Ingénieur environnement', 'en' => 'Environmental engineer'],
                ['fr' => 'Écologue', 'en' => 'Ecologist'],
                ['fr' => 'Chargé de projet développement durable', 'en' => 'Sustainability project officer'],
                ['fr' => 'Énergéticien', 'en' => 'Energy specialist'],
                ['fr' => 'Conseil en RSE', 'en' => 'CSR consultant'],
                ['fr' => 'Hydrogéologue', 'en' => 'Hydrogeologist'],
['fr' => 'Géologue', 'en' => 'Geologist'],
['fr' => 'Océanographe', 'en' => 'Oceanographer'],
['fr' => 'Météorologiste', 'en' => 'Meteorologist'],
['fr' => 'Éco-conseiller', 'en' => 'Eco-advisor'],
['fr' => 'Auditeur environnemental', 'en' => 'Environmental auditor'],
['fr' => 'Technicien en dépollution', 'en' => 'Decontamination technician'],
['fr' => 'Technicien de mesure de la qualité de l\'air', 'en' => 'Air quality technician'],
['fr' => 'Dépollueur de sols', 'en' => 'Soil remediation specialist'],
['fr' => 'Gestionnaire de déchets', 'en' => 'Waste manager'],
['fr' => 'Insécurité alimentaire / Sécurité sanitaire', 'en' => 'Food safety inspector'],
['fr' => 'Vulcanologue', 'en' => 'Volcanologist'],
            ],
            'renewable-energy' => [
                ['fr' => 'Technicien ENR', 'en' => 'Renewable energy technician'],
                ['fr' => 'Installateur de panneaux solaires', 'en' => 'Solar panel installer'],
                ['fr' => 'Technicien éolien', 'en' => 'Wind turbine technician'],
                ['fr' => 'Ingénieur en énergies renouvelables', 'en' => 'Renewable energy engineer'],
                ['fr' => 'Conseiller en efficacité énergétique', 'en' => 'Energy efficiency advisor'],
                ['fr' => 'Monteur d\'éoliennes', 'en' => 'Wind turbine erector'],
                ['fr' => 'Technicien de maintenance éolienne en hauteur', 'en' => 'Wind turbine height maintenance technician'],
                ['fr' => 'Installateur de pompes à chaleur', 'en' => 'Heat pump installer'],
                ['fr' => 'Installateur de panneaux solaires thermiques', 'en' => 'Thermal solar panel installer'],
                ['fr' => 'Installateur de géothermie domestique', 'en' => 'Domestic geothermal installer'],
                ['fr' => 'Technicien biomasse', 'en' => 'Biomass technician'],
                ['fr' => 'Installateur de récupération d\'eau de pluie', 'en' => 'Rainwater harvesting installer'],
                ['fr' => 'Conseiller en énergie solaire', 'en' => 'Solar energy advisor'],
            ],
            'water-sanitation' => [
                ['fr' => 'Technicien de l\'eau', 'en' => 'Water technician'],
                ['fr' => 'Égoutier', 'en' => 'Sewer worker'],
                ['fr' => 'Agent de station d\'épuration', 'en' => 'Wastewater treatment plant operator'],
                ['fr' => 'Ingénieur en traitement des eaux', 'en' => 'Water treatment engineer'],
                ['fr' => 'Plombier sanitaire', 'en' => 'Sanitary plumber'],
            ],
            'waste-management-recycling' => [
                ['fr' => 'Éboueur', 'en' => 'Garbage collector'],
                ['fr' => 'Agent de tri', 'en' => 'Sorting agent'],
                ['fr' => 'Technicien en valorisation', 'en' => 'Recycling technician'],
                ['fr' => 'Conducteur de benne', 'en' => 'Bin lorry driver'],
                ['fr' => 'Responsable de déchèterie', 'en' => 'Waste disposal site manager'],
            ],

            // ==================== SÉCURITÉ, DÉFENSE & URGENCE ====================
            'security-safety' => [
                ['fr' => 'Agent de sécurité', 'en' => 'Security guard'],
                ['fr' => 'Agent de sûreté', 'en' => 'Safety officer'],
                ['fr' => 'Responsable sécurité', 'en' => 'Security manager'],
                ['fr' => 'Agent de sécurité incendie', 'en' => 'Fire safety officer'],
                ['fr' => 'Vigile', 'en' => 'Security officer'],
                ['fr' => 'Opérateur de vidéosurveillance', 'en' => 'CCTV operator'],
            ],
            'private-security-surveillance' => [
                ['fr' => 'Agent de sécurité privée', 'en' => 'Private security agent'],
                ['fr' => 'Garde particulier', 'en' => 'Security guard'],
                ['fr' => 'Agent de surveillance', 'en' => 'Surveillance officer'],
                ['fr' => 'Responsable de site de surveillance', 'en' => 'Site security supervisor'],
            ],
            'firefighters-emergency-services' => [
                ['fr' => 'Pompier', 'en' => 'Firefighter'],
                ['fr' => 'Ambulancier', 'en' => 'Ambulance driver'],
                ['fr' => 'Sapeur-pompier professionnel', 'en' => 'Professional firefighter'],
                ['fr' => 'Officier de sapeurs-pompiers', 'en' => 'Fire officer'],
                ['fr' => 'Secouriste', 'en' => 'First responder'],
            ],
            'aerospace-defense' => [
                ['fr' => 'Ingénieur aéronautique', 'en' => 'Aeronautical engineer'],
                ['fr' => 'Mécanicien aéronautique', 'en' => 'Aircraft mechanic'],
                ['fr' => 'Technicien de maintenance aéronautique', 'en' => 'Aircraft maintenance technician'],
                ['fr' => 'Ingénieur en défense', 'en' => 'Defense engineer'],
                ['fr' => 'Opérateur de simulation de vol', 'en' => 'Flight simulator operator'],
            ],

            // ==================== AUTRES SECTEURS ====================
            'engineering' => [
                ['fr' => 'Ingénieur mécanique', 'en' => 'Mechanical engineer'],
                ['fr' => 'Ingénieur électrique', 'en' => 'Electrical engineer'],
                ['fr' => 'Ingénieur R&D', 'en' => 'R&D engineer'],
                ['fr' => 'Ingénieur qualité', 'en' => 'Quality engineer'],
                ['fr' => 'Ingénieur process', 'en' => 'Process engineer'],
                ['fr' => 'Ingénieur méthodes', 'en' => 'Methods engineer'],
                ['fr' => 'Ingénieur systèmes', 'en' => 'Systems engineer'],
                ['fr' => 'Ingénieur d\'affaires', 'en' => 'Business engineer'],
                ['fr' => 'Ingénieur d\'études', 'en' => 'Design engineer'],
            ],
            'sales-distribution' => [
                ['fr' => 'Représentant commercial', 'en' => 'Sales representative'],
                ['fr' => 'Responsable des ventes', 'en' => 'Sales manager'],
                ['fr' => 'Attaché commercial', 'en' => 'Sales executive'],
                ['fr' => 'Directeur commercial', 'en' => 'Sales director'],
                ['fr' => 'Technico-commercial', 'en' => 'Technical sales representative'],
                ['fr' => 'Business developer', 'en' => 'Business developer'],
                ['fr' => 'Agent commercial', 'en' => 'Commercial agent'],
                ['fr' => 'Responsable grands comptes', 'en' => 'Key account manager'],
                ['fr' => 'Chargé de développement commercial', 'en' => 'Business development officer'],
            ],
            'automotive' => [
                ['fr' => 'Mécanicien automobile', 'en' => 'Auto mechanic'],
                ['fr' => 'Vendeur automobile', 'en' => 'Car salesperson'],
                ['fr' => 'Carrossier', 'en' => 'Auto body repairer'],
                ['fr' => 'Peintre automobile', 'en' => 'Auto painter'],
                ['fr' => 'Technicien de diagnostic', 'en' => 'Diagnostic technician'],
                ['fr' => 'Responsable après-vente', 'en' => 'After-sales manager'],
            ],
            'electrical-energy' => [
                ['fr' => 'Électricien bâtiment', 'en' => 'Building electrician'],
                ['fr' => 'Technicien ENR', 'en' => 'Renewable energy technician'],
                ['fr' => 'Électrotechnicien', 'en' => 'Electrotechnician'],
                ['fr' => 'Technicien en éclairage public', 'en' => 'Public lighting technician'],
                ['fr' => 'Installateur en câblage', 'en' => 'Cable installer'],
            ],
            'hair-beauty' => [
                ['fr' => 'Coiffeur(se)', 'en' => 'Hairdresser'],
                ['fr' => 'Esthéticien(ne)', 'en' => 'Beautician'],
                ['fr' => 'Maquilleur(se)', 'en' => 'Makeup artist'],
                ['fr' => 'Manucure', 'en' => 'Nail technician'],
                ['fr' => 'Barbier', 'en' => 'Barber'],
                ['fr' => 'Prothésiste ongulaire', 'en' => 'Nail artist'],
            ],
            'craftsmanship-traditional-trades' => [
                ['fr' => 'Artisan d\'art', 'en' => 'Craftsman'],
                ['fr' => 'Bijoutier', 'en' => 'Jeweler'],
                ['fr' => 'Céramiste', 'en' => 'Ceramist'],
                ['fr' => 'Verrerie', 'en' => 'Glassblower'],
                ['fr' => 'Tapissier', 'en' => 'Upholsterer'],
                ['fr' => 'Maroquinier', 'en' => 'Leather worker'],
                ['fr' => 'Luthier', 'en' => 'Luthier'],
                ['fr' => 'Émailleur', 'en' => 'Enameler'],
            ],
            'social-solidarity-economy' => [
                ['fr' => 'Responsable d\'association', 'en' => 'Association manager'],
                ['fr' => 'Coordinateur de projet solidaire', 'en' => 'Solidarity project coordinator'],
                ['fr' => 'Animateur de coopérative', 'en' => 'Cooperative animator'],
                ['fr' => 'Chargé de mission ESS', 'en' => 'Social economy mission officer'],
            ],
            'coaching-personal-development' => [
                ['fr' => 'Coach professionnel', 'en' => 'Professional coach'],
                ['fr' => 'Coach en développement personnel', 'en' => 'Personal development coach'],
                ['fr' => 'Formateur en soft skills', 'en' => 'Soft skills trainer'],
                ['fr' => 'Consultant en management', 'en' => 'Management consultant'],
                ['fr' => 'Médiateur', 'en' => 'Mediator'],
            ],
            'insurance-risk-management' => [
                ['fr' => 'Assureur', 'en' => 'Insurance agent'],
                ['fr' => 'Gestionnaire de sinistres', 'en' => 'Claims handler'],
                ['fr' => 'Expert en sinistres', 'en' => 'Claims adjuster'],
                ['fr' => 'Courtier en assurances', 'en' => 'Insurance broker'],
                ['fr' => 'Responsable risques', 'en' => 'Risk manager'],
            ],
            'microfinance-financial-inclusion' => [
                ['fr' => 'Agent de crédit', 'en' => 'Loan officer'],
                ['fr' => 'Conseiller microfinance', 'en' => 'Microfinance advisor'],
                ['fr' => 'Chargé d\'inclusion financière', 'en' => 'Financial inclusion officer'],
                ['fr' => 'Gestionnaire de portefeuille microfinance', 'en' => 'Microfinance portfolio manager'],
            ],
            // ==================== COMMERCE, INFORMEL & ARTISANAT ====================
            'retail-commerce' => [
                ['fr' => 'Vendeur / Commerçant', 'en' => 'Shopkeeper / Salesperson'],
                ['fr' => 'Caissier(ère)', 'en' => 'Cashier'],
                ['fr' => 'Gérant de magasin', 'en' => 'Store manager'],
                ['fr' => 'Vendeur itinérant', 'en' => 'Itinerant vendor'],
                ['fr' => 'Marchand ambulant', 'en' => 'Street vendor'],
                ['fr' => 'Marchand de marché', 'en' => 'Market stall vendor'],
                ['fr' => 'Merchandiser', 'en' => 'Merchandiser'],
                ['fr' => 'Responsable rayon', 'en' => 'Category manager (retail)'],
                ['fr' => 'Responsable e-commerce', 'en' => 'E-commerce manager'],
            ],
            'informal-economy-street-trading' => [
                ['fr' => 'Réparateur de rue', 'en' => 'Street repairer'],
                ['fr' => 'Collecteur de déchets recyclables', 'en' => 'Waste picker / Recyclables collector'],
                ['fr' => 'Coursier informel', 'en' => 'Informal courier'],
                ['fr' => 'Chiffonnier', 'en' => 'Rag-and-bone collector'],
                ['fr' => 'Vendeur ambulant de nourriture', 'en' => 'Street food vendor'],
                ['fr' => 'Broyeur / récupérateur', 'en' => 'Scrap collector'],
                ['fr' => 'Aide occasionnel', 'en' => 'Casual laborer'],
            ],
            'textile-fashion' => [
                ['fr' => 'Couturier(ère)', 'en' => 'Tailor / Seamstress'],
                ['fr' => 'Modéliste', 'en' => 'Pattern maker'],
                ['fr' => 'Styliste / Designer de mode', 'en' => 'Fashion designer'],
                ['fr' => 'Retoucheur(se)', 'en' => 'Alterations tailor'],
                ['fr' => 'Brodeur', 'en' => 'Embroiderer'],
                ['fr' => 'Opérateur(rice) textile', 'en' => 'Textile machine operator'],
            ],
            'repair-maintenance-services' => [
                ['fr' => 'Réparateur électroménager', 'en' => 'Appliance repairer'],
                ['fr' => 'Réparateur de téléphones mobiles', 'en' => 'Mobile phone repairer'],
                ['fr' => 'Mécanicien vélo', 'en' => 'Bicycle mechanic'],
                ['fr' => 'Cordonnier', 'en' => 'Cobbler / Shoemaker'],
                ['fr' => 'Plombier indépendant', 'en' => 'Independent plumber'],
                ['fr' => 'Réparateur informatique', 'en' => 'Computer repair technician'],
                ['fr' => 'Technicien en électroménager', 'en' => 'Home appliance technician'],
            ],
            'education-training' => [
                ['fr' => 'Formateur(trice)', 'en' => 'Trainer'],
                ['fr' => 'Enseignant(e)', 'en' => 'Teacher'],
                ['fr' => 'Professeur', 'en' => 'Professor'],
                ['fr' => 'Instructeur', 'en' => 'Instructor'],
                ['fr' => 'Tuteur', 'en' => 'Tutor'],
                ['fr' => 'Coordinateur pédagogique', 'en' => 'Educational coordinator'],
            ],
            'humanitarian-logistics-emergency-relief' => [
                ['fr' => 'Logisticien humanitaire', 'en' => 'Humanitarian logistician'],
                ['fr' => 'Coordinateur d\'urgence', 'en' => 'Emergency coordinator'],
                ['fr' => 'Responsable de mission ONG', 'en' => 'NGO mission manager'],
                ['fr' => 'Acheteur humanitaire', 'en' => 'Humanitarian buyer'],
                ['fr' => 'Référent sécurité terrain', 'en' => 'Field security officer'],
            ],
        ];
    }
}